### ISSUE TITLE
go-drive是否支持其他上传方式？

### ISSUE THREAD

**Issue by MeowCold** [devld/go-drive#15]
比如webdav，s3 等，虽然看起来有点像套娃。但这些协议能让支持更多的客户端，也方便上传。

**Comment by MeowCold** [comment]
感谢回复

**Comment by devld** [comment]
Hi, WebDAV 访问方式已经实现了，下个版本就会包含进去。

**Comment by devld** [comment]
v0.5.0 已经发布

https://github.com/devld/go-drive/releases/tag/v0.5.0
