### ISSUE TITLE
请问window怎么添加本地文件?

### ISSUE THREAD

**Issue by sunday229** [devld/go-drive#26]
请问window怎么添加本地文件?

**Comment by devld** [comment]
在配置文件中，有一个 `free-fs` 的选项

https://github.com/devld/go-drive/blob/c77890570bbae7aa06bf03f5d9fa9d74ecdf1976/docs/config.yml#L54-L58

- 当未开启(`false`)时

  在管理界面创建 “本地文件” 的映射时，”根路径“是一个相对路径，相对于 “数据目录” 中的 `local` 文件夹。
  比如，假设数据目录为当前目录(`./`)，在 “根路径” 中填写的是 `aaa`，那么 `<数据目录>/local/aaa` 这个文件夹必须提前创建好。

- 当开启(`true`)时
  
  “本地文件” 配置中的 “根路径” 就是绝对路径，可以填写任意存在的目录的绝对路径（如 `D:\xxx\yyy`）


其中，数据目录可在 `config.yml` 中配置

https://github.com/devld/go-drive/blob/c77890570bbae7aa06bf03f5d9fa9d74ecdf1976/docs/config.yml#L27-L36

**Comment by sunday229** [comment]
> 在配置文件中，有一个 `free-fs` 的选项
> 
> https://github.com/devld/go-drive/blob/c77890570bbae7aa06bf03f5d9fa9d74ecdf1976/docs/config.yml#L54-L58
> 
> * 当未开启(`false`)时
>   在管理界面创建 “本地文件” 的映射时，”根路径“是一个相对路径，相对于 “数据目录” 中的 `local` 文件夹。
>   比如，假设数据目录为当前目录(`./`)，在 “根路径” 中填写的是 `aaa`，那么 `<数据目录>/local/aaa` 这个文件夹必须提前创建好。
> * 当开启(`true`)时
>   “本地文件” 配置中的 “根路径” 就是绝对路径，可以填写任意存在的目录的绝对路径（如 `D:\xxx\yyy`）
> 
> 其中，数据目录可在 `config.yml` 中配置
> 
> https://github.com/devld/go-drive/blob/c77890570bbae7aa06bf03f5d9fa9d74ecdf1976/docs/config.yml#L27-L36

谢谢,问题解决了,我再测试一下webdav和SSL 证书看看.
