### ISSUE TITLE
Onedrive能支持团队企业版吗

### ISSUE THREAD

**Issue by SexyBeast233** [devld/go-drive#29]
如题，发现只实现了个人onedrive登录上去了 ，也期待未来实现

**Comment by devld** [comment]
可以的，最近支持一下

**Comment by devld** [comment]
Hi, OneDrive 已经支持组织账户了，下个版本中就可以使用了。

**Comment by SexyBeast233** [comment]
太好了

**Comment by devld** [comment]
Hi, [v0.6.0](https://github.com/devld/go-drive/releases/tag/v0.6.0) 发布了
