### ISSUE TITLE
[bug] /lib64/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by jt9ge** [devld/go-drive#33]
操作系统：Centos:7.9  64bit

不想升级Centos libc 2.28,因为要安装这个，依赖的东西太多了，gcc也得升级，太烦了。

看作者能不否兼容一下低版本lib

**Comment by devld** [comment]
可以尝试用 docker 运行，不需要升级 glibc 版本。

或者手动在低版本机器上重新编译一下。
