### ISSUE TITLE
web文件夹运行后空白页面是什么原因?

### ISSUE THREAD

**Issue by TankTim68** [devld/go-drive#36]
go本地生成了exe运行起来，web文件夹本地：npm run dev也没报错，浏览器访问是空白页面，请问是什么原因。

**Comment by devld** [comment]
之前运行过这个吗？检查一下链接地址是什么。
上个版本修改过文件列表的路由地址，从 `#/files/` 改到了 `#/_/`。
如果确认是 `#/_/` ，麻烦看一下 F12 控制台有没有什么报错信息。

**Comment by TankTim68** [comment]
路径是：#/_/ 
`<html>
<body>


  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <script type="module" src="/@vite/client"></script>
  |  
  | <meta charset="UTF-8" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  | <link rel="icon" href="/static/icon/android-chrome-192x192.png" />
  | <title>
  | Drive
  | </title>
  | <link rel="stylesheet" href="/static/iconfont/iconfont.css" />
  |  
  | <script>
  | var ___config___ = {
  | api: '/api',
  | appName: 'Drive',
  | version: '',
  | }
  | </script>
  |  
  | </head>
  | <body>
  | <div id="app"></div>
  | <script type="module" src="/src/main.js"></script>
  | <script src="/static/iconfont/iconfont.js"></script>
  | </body>
  | </html>


</body>
</html><!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="[/@vite/client](http://localhost:9803/@vite/client)"></script>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="[/static/icon/android-chrome-192x192.png](http://localhost:9803/static/icon/android-chrome-192x192.png)" />
    <title>
      Drive
    </title>
    <link rel="stylesheet" href="[/static/iconfont/iconfont.css](http://localhost:9803/static/iconfont/iconfont.css)" />
    
    <script>
      var ___config___ = {
        api: '/api',
        appName: 'Drive',
        version: '',
      }
    </script>
    
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="[/src/main.js](http://localhost:9803/src/main.js)"></script>
    <script src="[/static/iconfont/iconfont.js](http://localhost:9803/static/iconfont/iconfont.js)"></script>
  </body>
</html>`

**Comment by TankTim68** [comment]
确认路径就是是 #/_/
控制台都没有报错。

**Comment by TankTim68** [comment]
http://127.0.0.1%7B%7B%20.config.apipath%20%7D%7D/auth/init  请求后端的URL成这样了。

**Comment by devld** [comment]
`index.html` 最终会经过 Go 的模板引擎处理，注入一些变量。
大概在这里：
https://github.com/devld/go-drive/blob/d0d3fff9b6517aef11a9a5c10783a08aa2268d79/web/index.html#L12-L18

静态文件是通过什么来访问的呢？`go-drive` 本身，还是 `nginx`，还是其他什么的？

**Comment by TankTim68** [comment]
`<html>
<body>


<script>
--
  | var ___config___ = {
  | api: '/api',
  | appName: 'Drive',
  | version: '',
  | }
  | </script>


</body>
</html>`

web/index.html 这个是直接nodejs npm run dev运行。
感谢回复。

**Comment by devld** [comment]
理论上，直接 `npm run dev` 就不会使用注入的变量了。

https://github.com/devld/go-drive/blob/d0d3fff9b6517aef11a9a5c10783a08aa2268d79/web/index.html#L19-L27

这种情况我没法复现。

nodejs 的版本是什么呢？

**Comment by TankTim68** [comment]
已经可以了，非常感谢
