### ISSUE TITLE
任务计划

### ISSUE THREAD

**Issue by loveqianool** [devld/go-drive#43]
有没有可能实现任务计划功能，定时在盘与盘之间移动复制文件，用来备份或分发证书之类的。

**Comment by devld** [comment]
可以实现，我考虑一下怎样实现比较好。

**Comment by devld** [comment]
计划任务在 [v0.8.0](https://github.com/devld/go-drive/releases) 中实现了，可在 `管理员` -> `任务` 中进行配置。

不过目前为了灵活度，只支持写 js 脚本来做一些操作。

**Comment by devld** [comment]
我再优化优化，只支持代码方式确实不太合适😂。

感谢，不过暂时不考虑赞助了，现在就只是写着玩玩。

简单的复制可以这样写
```js
// 将 a/xxx 复制到 b/xxx，第三个参数表示覆盖，如果第三个参数是 false，将会自动重命名
cp('a/xxx', 'b', true)

// 将 a/xxx 复制到 b/yyy
cp('a/xxx', 'b/yyy', true)
//
```

**Comment by devld** [comment]
这个需要换其他账户登录，最好不要用 root 来跑这个。
