### ISSUE TITLE
docker下修改监听端口的问题

### ISSUE THREAD

**Issue by wimdaw** [devld/go-drive#45]
在docker下修改了配置文件的监听端口 ，docker重启后怎么还是监听的8089？

**Comment by wimdaw** [comment]
是否要 先删除docker重新运行？

**Comment by devld** [comment]
docker 应该就没必要更换端口了吧，那样修改的只是容器内的端口号。

从外部访问的端口可以通过 docker 的端口映射。

`-p 1234:8089`

**Comment by wimdaw** [comment]
我现在是内部和外部的8089都被占用了

**Comment by devld** [comment]
> 我现在是内部和外部的8089都被占用了

容器停止后，容器外映射的就不会占用了。


> 就是说内外监听端口一起改

容器内的一般没必要修改，改了也没有意义。

`-p 1234:8089`

这个的意思就是访问本地的 1234 端口时，会被转发到容器内的 8089 端口，所以本地的 1234 端口会被占用。

**Comment by wimdaw** [comment]
懂了，我配置完盘之后上传老是错误是什么问题呢，没有 设置权限嘛

**Comment by devld** [comment]
根目录是无法上传的，如果是其他目录上传文件出错了，需要看一下日志。
```bash
docker logs 容器id
```

**Comment by wimdaw** [comment]
![QQ截图20220906072824](https://user-images.githubusercontent.com/29478061/188520417-7006e738-8794-4a3b-bcd1-bdfe0901f454.jpg)

**Comment by wimdaw** [comment]
这是错误信息

**Comment by devld** [comment]
是什么类型的盘呢？

**Comment by wimdaw** [comment]
Onedrive国际版

**Comment by devld** [comment]
是个 bug，请更新一下 [v0.7.1](https://github.com/devld/go-drive/releases)。

**Comment by wimdaw** [comment]
![QQ截图20220907083018](https://user-images.githubusercontent.com/29478061/188762968-7f40f305-acd3-4159-8565-64b73d82e698.jpg)
上传没问题了，这个一直not found正常嘛？

**Comment by wimdaw** [comment]
![QQ截图20220907083613](https://user-images.githubusercontent.com/29478061/188763527-47e83cec-53ea-4a5a-a60b-9c8e68cf9e9c.jpg)
配置文件好像没有这行，自己加可以嘛，还有能不能传文件夹呢

**Comment by wimdaw** [comment]
配置文件能直接在后台修改嘛，我直接去容器里面修改了就没法启动了，不知道是不是有bug

**Comment by devld** [comment]
> ![QQ截图20220907083018](https://user-images.githubusercontent.com/29478061/188762968-7f40f305-acd3-4159-8565-64b73d82e698.jpg) 上传没问题了，这个一直not found正常嘛？

正常



> ![QQ截图20220907083613](https://user-images.githubusercontent.com/29478061/188763527-47e83cec-53ea-4a5a-a60b-9c8e68cf9e9c.jpg) 配置文件好像没有这行，自己加可以嘛，还有能不能传文件夹呢

回调 URL，默认就是这个，不用加。
只能上传非空文件夹，空文件夹会被忽略。



> 配置文件能直接在后台修改嘛，我直接去容器里面修改了就没法启动了，不知道是不是有bug

需要看日志，是否报错；是否配置文件修改的有问题。
