### ISSUE TITLE
在局域网中部署，挂载本地文件，pdf无法正常加载

### ISSUE THREAD

**Issue by XiaoPika** [devld/go-drive#47]
电脑插互联网网线测试是没问题的，改成插局域网的网线就会出现如下图这种问题，pdf是空白，图片和视频的预览没有问题。
环境：Windows 10 pro x64
运行版本：release 0.8.2 go-drive_windows_amd64 
麻烦大佬有空指教一下！感激不尽
![1](https://user-images.githubusercontent.com/10910848/204208893-ab7a98cd-5bfa-4dfe-a1d0-3ae795844225.png)

**Comment by devld** [comment]
浏览器版本是？

**Comment by XiaoPika** [comment]
> 浏览器版本是？
> 
> 看样子是浏览器版本有点低了，pdf.js 里用了较新的 js 语法。

感谢大佬回复！版本是Google Chrome 83.0.4103.106，确实比较低了；局域网环境太多终端都是旧版浏览器，不方便更新。
不过现在大都数浏览器原生支持预览pdf，我能否把pdf的预览直接更改为下载呢？我看管理员的后台配置项里并没有pdf的预览控制

**Comment by devld** [comment]
等一会儿我将 pdf.js 换成支持旧版浏览器的应该就好了

**Comment by devld** [comment]
[v0.8.3](https://github.com/devld/go-drive/releases) 已经换成了支持旧版浏览器的 pdf.js，你试一下
