### ISSUE TITLE
Google Drive: Shared drives not listed!

### ISSUE THREAD

**Issue by chiphu** [devld/go-drive#50]
I configured to list a shared drive from Google drive but it's not shown. How come?

**Comment by devld** [comment]
You can click the 'Reload drives' button after making any changes.

**Comment by chiphu** [comment]
> You can click the 'Reload drives' button after making any changes.
I did it several times before commenting this issue but it still lists 'root' drives, not shared drives.

**Comment by devld** [comment]
Does the page show 'root' and the list is empty?

**Comment by chiphu** [comment]
Yes, the page shows Root and the list is NOT empty. Here's my screenshot:

![image](https://user-images.githubusercontent.com/90211256/210369841-17d3c692-4919-4fd5-9626-2aa258ec1bea.png)

**Comment by devld** [comment]
Each `Drive` added will only show the corresponding `Drive` entry on the page.

You need to create a separate `Drive` for your Shared Drive.
You can select your Shared Drive from the Drive's configuration page.

![image](https://user-images.githubusercontent.com/11621816/210483004-edd67408-bb75-4505-9051-14ef9db31c01.png)

But this feature has not been fully tested.

**Comment by chiphu** [comment]
> Each `Drive` added will only show the corresponding `Drive` entry on the page.
> 
> You need to create a separate `Drive` for your Shared Drive. You can select your Shared Drive from the Drive's configuration page.
> 
> ![image](https://user-images.githubusercontent.com/11621816/210483004-edd67408-bb75-4505-9051-14ef9db31c01.png)
> 
> But this feature has not been fully tested.
Thanks dev. I did choose the name of those shared drives, but it still shows the content/files of My Drive, not the ones of the shared drives.

**Comment by devld** [comment]
Sorry. It's a bug. This feature has not been fully tested. I'll fix it soon.

**Comment by chiphu** [comment]
> Sorry. It's a bug. This feature has not been fully tested. I'll fix it soon.
Thank you, dev. Look forward to it!
