### ISSUE TITLE
每次点击目录进去都会出现500

### ISSUE THREAD

**Issue by Michelangelo-li** [devld/go-drive#75]
用户登录进去然后点击目录就提示500  服务器错误 然后点返回在点击目录进去就可以了  这个是什么原因

**Comment by Michelangelo-li** [comment]
![Uploading 8ea279c66bdfc67931661d0d1c0e5a7.jpg…]()
![Uploading 8ea279c66bdfc67931661d0d1c0e5a7.jpg…]()

**Comment by Michelangelo-li** [comment]
![Uploading 8ea279c66bdfc67931661d0d1c0e5a7.jpg…]()

**Comment by devld** [comment]
请提供具体的错误信息，当鼠标悬浮在错误页面中的错误码上时，会提示具体的错误信息；

或者提供一下报错时服务端的日志。
