### ISSUE TITLE
Support oss and cos

### ISSUE THREAD

**Issue by GaryHuangBD** [devld/go-drive#8]
Hi, is there any plans to add new cloude storages, such as tentcent cos, alibaba oss etc
I'm tring to expand it.

**Comment by devld** [comment]
Tencent COS and Aliyun OSS are compatible with S3 protocol, but there's some configuration that should be made.

https://www.alibabacloud.com/help/en/doc-detail/64919.htm

**Comment by GaryHuangBD** [comment]
yeah, i knew it. 
I'll have a try tomrrow.

**Comment by GaryHuangBD** [comment]
tested， LGTM~
Any contact info about u? pls tell me by email, for talking about this project, thank u.
